# Generated by Django 4.2.1 on 2023-06-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user_order_number",
            field=models.IntegerField(auto_created=True, default=None),
        ),
    ]
