# Generated by Django 4.2.1 on 2023-06-28 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_user_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user_order_number",
        ),
    ]
