# Generated by Django 4.2.1 on 2023-05-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dorm_number',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='room_number',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
