# Generated by Django 4.2.1 on 2023-06-10 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dinnerware', '0001_initial'),
        ('products', '0001_initial'),
        ('account', '0002_profile_dorm_number_profile_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='products.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDinnerware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dinnerware_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinnerware_id', to='dinnerware.dinnerware')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinnerware_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
