# Generated by Django 4.2.1 on 2023-06-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDinnerware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dinnerware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dinnerware_category', to='dinnerware.categorydinnerware')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='categorydinnerware',
            index=models.Index(fields=['name'], name='dinnerware__name_ceaf36_idx'),
        ),
        migrations.AddIndex(
            model_name='dinnerware',
            index=models.Index(fields=['id', 'slug'], name='dinnerware__id_690be4_idx'),
        ),
        migrations.AddIndex(
            model_name='dinnerware',
            index=models.Index(fields=['name'], name='dinnerware__name_b41574_idx'),
        ),
        migrations.AddIndex(
            model_name='dinnerware',
            index=models.Index(fields=['-created'], name='dinnerware__created_0eb589_idx'),
        ),
    ]
