# Generated by Django 4.2.1 on 2023-06-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("cooking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="available",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="composition",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="price",
        ),
        migrations.CreateModel(
            name="DishComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, default=1)),
                ("weigth", models.FloatField(blank=True)),
                ("volume", models.PositiveBigIntegerField(blank=True, default=1000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "dish",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cooking.dish",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dish_product",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
