# Generated by Django 4.2.1 on 2023-06-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cooking", "0002_remove_dish_available_remove_dish_composition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishcomposition",
            name="quantity",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="dishcomposition",
            name="volume",
            field=models.PositiveBigIntegerField(blank=True),
        ),
    ]
