# Generated by Django 4.2.1 on 2023-06-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cooking", "0003_alter_dishcomposition_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishcomposition",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dishcomposition",
            name="volume",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dishcomposition",
            name="weigth",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
